// LOCALHOST USERS
###
GET http://localhost:8080/users HTTP/1.1


### Get user by username
GET http://localhost:8080/users/pharo HTTP/1.1
###
GET http://localhost:8080/users/skanty HTTP/1.1
###
GET http://localhost:8080/users/papa_bills HTTP/1.1



### Create single contact
POST http://localhost:8080/users HTTP/1.1 
content-type: application/json

{
    "username": "moni hunter",
    "name": "Sulley Alhassan",
    "email": "monihunter1@gmail.com",
    "password": "MoNeY_11",
    "roles": ["user"],
    "permissions": ["read"],
    "title": "Laundry",
    "tasks": ["Wash clothes", "Iron clothes", "Fold and arrange clothes"]
}

### Edit Single user 
PUT http://localhost:8080/users/65351dd92d7ed4cc5f298662 HTTP/1.1 
content-type: application/json

{
    "username" :"bills",
    "name": "Theophilus Akahoho",
    "email": "papabills@gmail.com",
    "password": "TakeitSlow",
    "roles": ["user"],
    "permissions": ["read"],
    "title": "Work",
    "tasks": ["Service car", "Go for rounds", "Go for goods"]
}

### DELETE single user 
DELETE http://localhost:8080/users/65351dffebe849068b008e97 HTTP/1.1



// LOCALHOST TASKS
###
GET http://localhost:8080/task HTTP/1.1

### Get task by name
GET http://localhost:8080/task/development HTTP/1.1
###
GET http://localhost:8080/task/event HTTP/1.1
###
GET http://localhost:8080/task/routine HTTP/1.1


### Create single task
POST http://localhost:8080/task HTTP/1.1 
content-type: application/json

{
    "name": "assignment",
    "description": "This is a task do and submit a particular coding assignment",
    "dueDate": "2023-10-15",
    "priority": "High",
    "status": "In Progress",
    "assignedUser": 1,
    "notes": "This task requires special attention, coordination and collaboration between team members"
}

### Edit Single task 

PUT http://localhost:8080/task/65293a68f08455e0eb68b13d HTTP/1.1 
content-type: application/json

{
    "name": "function",
    "description": "This is a task to plan an event.",
    "dueDate": "2023-10-24",
    "priority": "High",
    "status": "Not Started",
    "assignedUser": 2,
    "notes": "This task requires special effort and dedication"
}

### DELETE single task 
DELETE http://localhost:8080/task/65351ef91b061591c643ae84 HTTP/1.1











// PRODUCTION Deployment

// Production Users
###
GET https://task-manager-t3rr.onrender.com/users HTTP/1.1


### Get user by username
GET https://task-manager-t3rr.onrender.com/users/pharo HTTP/1.1
###
GET https://task-manager-t3rr.onrender.com/users/skanty HTTP/1.1
###
GET https://task-manager-t3rr.onrender.com/users/papa bills HTTP/1.1


### Create single user
POST https://task-manager-t3rr.onrender.com/users HTTP/1.1 
content-type: application/json

{
    "username": "moni hunter",
    "name": "Sulley Alhassan",
    "email": "monihunter1@gmail.com",
    "password": "MoNeY_11",
    "roles": ["user"],
    "permissions": ["read"],
    "title": "Laundry",
    "tasks": ["Wash clothes", "Iron clothes", "Fold and arrange clothes"]
}

### Edit Single user 
PUT https://task-manager-t3rr.onrender.com/users/papa bills HTTP/1.1 
content-type: application/json

{
    "username": "De papa",
    "name": "Theophilus Akahoho",
    "email": "papabills@gmail.com",
    "password": "TakeitSlow",
    "roles": ["user"],
    "permissions": ["read"],
    "title": "Work",
    "tasks": ["Service car", "Go for rounds", "Go for goods"]
}

### DELETE single user 
DELETE https://task-manager-t3rr.onrender.com/users/moni hunter HTTP/1.1

// Production TASKS
###
GET https://task-manager-t3rr.onrender.com/task HTTP/1.1

### Get task by name
GET https://task-manager-t3rr.onrender.com/task/development HTTP/1.1
###
GET https://task-manager-t3rr.onrender.com/task/event HTTP/1.1
###
GET https://task-manager-t3rr.onrender.com/task/routine HTTP/1.1


### Create single task
POST https://task-manager-t3rr.onrender.com/task HTTP/1.1 
content-type: application/json

{
    "name": "assignment",
    "description": "This is a task do and submit a particular coding assignment",
    "dueDate": "2023-10-15",
    "priority": "High",
    "status": "In Progress",
    "assignedUser": 1,
    "notes": "This task requires special attention, coordination and collaboration between team members"
}

### Edit Single task 

PUT https://task-manager-t3rr.onrender.com/task/event HTTP/1.1 
content-type: application/json

{
    "name": "function",
    "description": "This is a task to plan an event.",
    "dueDate": "2023-10-24",
    "priority": "High",
    "status": "Not Started",
    "assignedUser": 2,
    "notes": "This task requires special effort and dedication"
}

### DELETE single task 
DELETE https://task-manager-t3rr.onrender.com/assignment HTTP/1.1

