// LOCALHOST USERS
###
GET http://localhost:8080/users HTTP/1.1


### Get user by username
GET http://localhost:8080/users/pharo HTTP/1.1
###
GET http://localhost:8080/users/skanty HTTP/1.1
###
GET http://localhost:8080/users/papa bills HTTP/1.1


### Create single contact
POST http://localhost:8080/users HTTP/1.1 
content-type: application/json

{
    "username": "moni hunter",
    "name": "Sulley Alhassan",
    "email": "monihunter1@gmail.com",
    "password": "MoNeY_11",
    "roles": ["user"],
    "permissions": ["read"],
    "title": "Laundry",
    "tasks": ["Wash clothes", "Iron clothes", "Fold and arrange clothes"]
}

### Edit Single user 
PUT http://localhost:8080/users/papa bills HTTP/1.1 
content-type: application/json

{
    "username": "De papa",
    "name": "Theophilus Akahoho",
    "email": "papabills@gmail.com",
    "password": "TakeitSlow",
    "roles": ["user"],
    "permissions": ["read"],
    "title": "Work",
    "tasks": ["Service car", "Go for rounds", "Go for goods"]
}


// LOCALHOST TASKS
###
GET http://localhost:8080/task HTTP/1.1

### Get task by name
GET http://localhost:8080/task/development HTTP/1.1
###
GET http://localhost:8080/task/event HTTP/1.1
###
GET http://localhost:8080/task/routine HTTP/1.1


### Create single task
POST http://localhost:8080/task HTTP/1.1 
content-type: application/json

{
    "name": "assignment",
    "description": "This is a task do and submit a particular coding assignment",
    "dueDate": "2023-10-15",
    "priority": "High",
    "status": "In Progress",
    "assignedUser": 1,
    "notes": "This task requires special attention, coordination and collaboration between team members"
}

### Edit Single task 

PUT http://localhost:8080/task/event HTTP/1.1 
content-type: application/json

{
    "name": "function",
    "description": "This is a task to plan an event.",
    "dueDate": "2023-10-24",
    "priority": "High",
    "status": "Not Started",
    "assignedUser": 2,
    "notes": "This task requires special effort and dedication"
}












// PRODUCTION Deploy
###

###Get Contacts by ID
GET https://cse341-wilson.onrender.com/contacts

###
GET https://cse341-wilson.onrender.com/contacts/651561fd3c8ebf6904fb39ec

###
GET https://cse341-wilson.onrender.com/contacts/651561fd3c8ebf6904fb39ed

###
GET https://cse341-wilson.onrender.com/contacts/651561fd3c8ebf6904fb39ee


### Create single contact
POST https://cse341-wilson.onrender.com/contacts HTTP/1.1 
content-type: application/json

{
"firstName":"Lucas", "lastName":"Kuma", "email":"Lucas1@gmail.com", "favoriteColor":"Red", "birthday":"05/10/1991"
}

### Edit Single contact 
PUT https://cse341-wilson.onrender.com/contacts/651e3afbfc0bbcabff9eef6c HTTP/1.1 
content-type: application/json

{
"firstName":"Lucas", "lastName":"Kumah", "email":"testnew@gmail.com", "favoriteColor":"Black", "birthday":"05/10/1991"
} 

### DELETE single contact 
DELETE https://cse341-wilson.onrender.com/contacts/651e3afbfc0bbcabff9eef6c HTTP/1.1



